@KC_HOST = http://localhost:8080
@KC_REALM = ezbud
@KC_TOKEN_ENDPOINT = {{KC_HOST}}/realms/{{KC_REALM}}/protocol/openid-connect/token
@CLIENT = ezbud
@USERNAME = admin
@PASSWORD = admin

POST {{KC_HOST}}/realms/{{KC_REALM}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{CLIENT}}&username={{USERNAME}}&password={{PASSWORD}}

###