@KC_HOST = http://localhost:8080
@KC_REALM = ezbud
@KC_TOKEN_ENDPOINT = {{KC_HOST}}/realms/{{KC_REALM}}/protocol/openid-connect/token
@CLIENT = admin-cli
@CLIENT_SECRET = MbPkK5ZNeGDZn5vYXS7tVPuiPrWaVRnk
@USERNAME = admin
@PASSWORD = admin

POST {{KC_HOST}}/realms/{{KC_REALM}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{CLIENT}}&client_secret={{CLIENT_SECRET}}

###
